using System;
using System.IO;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Mono.Cecil;
using Mono.Cecil.Cil;

namespace AutoDI.Fody.Tests
{
    extern alias AutoDIFody;

    [TestClass]
    public class CSharpCodeGeneratorTests
    {
        private string _outputDirectory;

        [TestInitialize]
        public void TestSetup()
        {
            _outputDirectory = Path.Combine(".", Path.GetRandomFileName());
        }

        [TestCleanup]
        public void TestCleanup()
        {
            Directory.Delete(_outputDirectory, true);
        }

        [TestMethod]
        public void CanGenerateClassWithConstructor()
        {
            TypeDefinition type = new TypeDefinition("name.space", "testtype", TypeAttributes.Public | TypeAttributes.Class);
            MethodDefinition ctor =
                new MethodDefinition(".ctor", MethodAttributes.Public | MethodAttributes.SpecialName | MethodAttributes.RTSpecialName, type)
                {
                    DeclaringType = type
                };

            var generator = new AutoDIFody::AutoDI.Fody.CodeGen.CSharpCodeGenerator(_outputDirectory);
            var ctorGenerator = generator.Method(ctor);

            ctorGenerator.Append("{" + Environment.NewLine + "}", Instruction.Create(OpCodes.Nop));

            generator.Save();
            
            string result = File.ReadAllText(Directory.EnumerateFiles(_outputDirectory).Single());

            string expected = 
                "namespace name.space" + Environment.NewLine + 
                "{" + Environment.NewLine + 
                "    public class testtype" + Environment.NewLine +
                "    {" + Environment.NewLine +
                "        //Generated by AutoDI" + Environment.NewLine +
                "        public testtype()" + Environment.NewLine +
                "        {" + Environment.NewLine + 
                "            {" + Environment.NewLine + 
                "            }" + Environment.NewLine + 
                "            //We now return you to your regularly scheduled method" + Environment.NewLine + 
                "        }" + Environment.NewLine + 
                "    }" + Environment.NewLine + 
                "}" + Environment.NewLine;
            Assert.AreEqual(expected, result);
            var sequencePoint = ctor.DebugInformation.SequencePoints.First();
            Assert.AreEqual(7, sequencePoint.StartLine);
            Assert.AreEqual(8, sequencePoint.EndLine);
            Assert.AreEqual(13, sequencePoint.StartColumn);
            Assert.AreEqual(14, sequencePoint.EndColumn);
        }
    }
}