using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoDI.AssemblyGenerator;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Mono.Cecil;
using Mono.Cecil.Cil;
using Mono.Cecil.Rocks;

namespace AutoDI.Fody.Tests
{
    extern alias AutoDIFody;

    [TestClass]
    public class CSharpCodeGeneratorTests
    {
        private static ModuleDefinition _testModule;
        private string _outputDirectory;

        [ClassInitialize]
        public static async Task Initialize(TestContext context)
        {
            var gen = new Generator();

            _testModule = (await gen.Execute()).SingleModule();
        }
        
        [TestInitialize]
        public void TestSetup()
        {
            _outputDirectory = Path.Combine(".", Path.GetRandomFileName());
        }

        [TestCleanup]
        public void TestCleanup()
        {
            if (Directory.Exists(_outputDirectory))
            {
                Directory.Delete(_outputDirectory, true);
            }
        }

        [TestMethod]
        public void ConstructorWithSingleParameterGeneratesExpectedSequencePoints()
        {
            TypeDefinition type = _testModule.GetType(
                $"{nameof(CSharpCodeGenrationTestsNamespace)}.{nameof(CSharpCodeGenrationTestsNamespace.Class1)}");
            MethodDefinition ctor = type.GetConstructors().Single();

            var generator = new AutoDIFody::AutoDI.Fody.CodeGen.CSharpCodeGenerator(_outputDirectory);
            var ctorGenerator = generator.Method(ctor);

            ctorGenerator.Append("if (foo == null)", Instruction.Create(OpCodes.Nop));
            ctorGenerator.Append(Environment.NewLine + "{" + Environment.NewLine);
            ctorGenerator.Append("    foo = GlobalDI.GetService<IService>();", Instruction.Create(OpCodes.Nop));
            ctorGenerator.Append(Environment.NewLine);
            ctorGenerator.Append("}", Instruction.Create(OpCodes.Nop));
            ctorGenerator.Append(Environment.NewLine);

            generator.Save();

            Assert.AreEqual(3, ctor.DebugInformation.SequencePoints.Count);

            SequencePoint first = ctor.DebugInformation.SequencePoints[0];
            Assert.AreEqual(8, first.StartLine);
            Assert.AreEqual(8, first.EndLine);
            Assert.AreEqual(13, first.StartColumn);
            Assert.AreEqual(29, first.EndColumn);
            SequencePoint second = ctor.DebugInformation.SequencePoints[1];
            Assert.AreEqual(10, second.StartLine);
            Assert.AreEqual(10, second.EndLine);
            Assert.AreEqual(17, second.StartColumn);
            Assert.AreEqual(55, second.EndColumn);
            SequencePoint third = ctor.DebugInformation.SequencePoints[2];
            Assert.AreEqual(11, third.StartLine);
            Assert.AreEqual(11, third.EndLine);
            Assert.AreEqual(13, third.StartColumn);
            Assert.AreEqual(14, third.EndColumn);
        }

        [TestMethod]
        public void CanGenerateClassWithPublicConstructor()
        {
            TypeDefinition type = _testModule.GetType(
                $"{nameof(CSharpCodeGenrationTestsNamespace)}.{nameof(CSharpCodeGenrationTestsNamespace.Class1)}");
            MethodDefinition ctor = type.GetConstructors().Single();

            var generator = new AutoDIFody::AutoDI.Fody.CodeGen.CSharpCodeGenerator(_outputDirectory);
            var ctorGenerator = generator.Method(ctor);

            ctorGenerator.Append("if (foo == null)", Instruction.Create(OpCodes.Nop));
            ctorGenerator.Append(Environment.NewLine + "{" + Environment.NewLine);
            ctorGenerator.Append("    foo = GlobalDI.GetService<IService>();", Instruction.Create(OpCodes.Nop));
            ctorGenerator.Append(Environment.NewLine);
            ctorGenerator.Append("}", Instruction.Create(OpCodes.Nop));
            ctorGenerator.Append(Environment.NewLine);

            generator.Save();
            
            string result = File.ReadAllText(Directory.EnumerateFiles(_outputDirectory).Single());

            string expected =
                "namespace " + nameof(CSharpCodeGenrationTestsNamespace) + Environment.NewLine + 
                "{" + Environment.NewLine + 
                "    public class " + nameof(CSharpCodeGenrationTestsNamespace.Class1) + Environment.NewLine +
                "    {" + Environment.NewLine +
                "        //Generated by AutoDI" + Environment.NewLine +
                $"        public {nameof(CSharpCodeGenrationTestsNamespace.Class1)}({nameof(CSharpCodeGenrationTestsNamespace)}.{nameof(CSharpCodeGenrationTestsNamespace.IService)} foo)" + Environment.NewLine +
                "        {" + Environment.NewLine + 
                "            if (foo == null)" + Environment.NewLine + 
                "            {" + Environment.NewLine + 
                "                foo = GlobalDI.GetService<IService>();" + Environment.NewLine + 
                "            }" + Environment.NewLine + 
                "            //We now return you to your regularly scheduled method" + Environment.NewLine + 
                "        }" + Environment.NewLine + 
                "    }" + Environment.NewLine + 
                "}" + Environment.NewLine;
            Assert.AreEqual(expected, result);
        }

        [TestMethod]
        public void CanGetMethodPublicProtectionModifier()
        {
            TypeDefinition type = _testModule.GetType(
                $"{nameof(CSharpCodeGenrationTestsNamespace)}.{nameof(CSharpCodeGenrationTestsNamespace.Class1)}");
            MethodDefinition ctor = type.GetConstructors().Single();

            Assert.AreEqual("public", AutoDIFody::AutoDI.Fody.TypeReferenceMixins.ProtectionModifierCSharp(ctor.Attributes));
        }

        [TestMethod]
        public void CanGetMethodInternalProtectionModifier()
        {
            TypeDefinition type = _testModule.GetType(
                $"{nameof(CSharpCodeGenrationTestsNamespace)}.{nameof(CSharpCodeGenrationTestsNamespace.Class2)}");
            MethodDefinition ctor = type.GetConstructors().Single();

            Assert.AreEqual("internal", AutoDIFody::AutoDI.Fody.TypeReferenceMixins.ProtectionModifierCSharp(ctor.Attributes));
        }

        [TestMethod]
        public void CanGetMethodProtectedInternalProtectionModifier()
        {
            TypeDefinition type = _testModule.GetType(
                $"{nameof(CSharpCodeGenrationTestsNamespace)}.{nameof(CSharpCodeGenrationTestsNamespace.Class3)}");
            MethodDefinition ctor = type.GetConstructors().Single();

            Assert.AreEqual("protected internal", AutoDIFody::AutoDI.Fody.TypeReferenceMixins.ProtectionModifierCSharp(ctor.Attributes));
        }

        [TestMethod]
        public void CanGetMethodProtectedProtectionModifier()
        {
            TypeDefinition type = _testModule.GetType(
                $"{nameof(CSharpCodeGenrationTestsNamespace)}.{nameof(CSharpCodeGenrationTestsNamespace.Class4)}");
            MethodDefinition ctor = type.GetConstructors().Single();

            Assert.AreEqual("protected", AutoDIFody::AutoDI.Fody.TypeReferenceMixins.ProtectionModifierCSharp(ctor.Attributes));
        }

        [TestMethod]
        public void CanGetMethodPrivateProtectedProtectionModifier()
        {
            TypeDefinition type = _testModule.GetType(
                $"{nameof(CSharpCodeGenrationTestsNamespace)}.{nameof(CSharpCodeGenrationTestsNamespace.Class5)}");
            MethodDefinition ctor = type.GetConstructors().Single();

            Assert.AreEqual("private protected", AutoDIFody::AutoDI.Fody.TypeReferenceMixins.ProtectionModifierCSharp(ctor.Attributes));
        }

        [TestMethod]
        public void CanGetMethodPrivatedProtectionModifier()
        {
            TypeDefinition type = _testModule.GetType(
                $"{nameof(CSharpCodeGenrationTestsNamespace)}.{nameof(CSharpCodeGenrationTestsNamespace.Class6)}");
            MethodDefinition ctor = type.GetConstructors().Single();

            Assert.AreEqual("private", AutoDIFody::AutoDI.Fody.TypeReferenceMixins.ProtectionModifierCSharp(ctor.Attributes));
        }

        [DataTestMethod]
        [DataRow("public", "Public")]
        [DataRow("internal", "Internal")]
        [DataRow("protected internal", "ProtectedInternal")]
        [DataRow("protected", "Protected")]
        [DataRow("private protected", "PrivateProtected")]
        [DataRow("private", "Private")]
        public void CanGetClassProtectionModifier(string modifier, string className)
        {
            TypeDefinition type = _testModule.GetType(
                $"{nameof(CSharpCodeGenrationTestsNamespace)}.{className}");

            TypeDefinition nestedType = _testModule.GetType(
                $"{nameof(CSharpCodeGenrationTestsNamespace)}.{nameof(CSharpCodeGenrationTestsNamespace.ClassProtectedModifiers)}/{className}");

            Assert.AreEqual(modifier, AutoDIFody::AutoDI.Fody.TypeReferenceMixins.ProtectionModifierCSharp(nestedType.Attributes));
            if (type != null)
            {
                Assert.AreEqual(modifier, AutoDIFody::AutoDI.Fody.TypeReferenceMixins.ProtectionModifierCSharp(type.Attributes));
            }
        }

    }

    //<assembly>
    //<ref: AutoDI />
    namespace CSharpCodeGenrationTestsNamespace
    {
        using AutoDI;

        public interface IService
        { }

        public class Class1
        {
            public Class1([Dependency]IService foo = null)
            {
                
            }
        }

        public class Class2
        {
            internal Class2([Dependency]IService foo = null)
            {
                
            }
        }

        public class Class3
        {
            protected internal Class3([Dependency]IService foo = null)
            {

            }
        }

        public class Class4
        {
            protected Class4([Dependency]IService foo = null)
            {

            }
        }

        public class Class5
        {
            private protected Class5([Dependency]IService foo = null)
            {

            }
        }

        public class Class6
        {
            private Class6([Dependency]IService foo = null)
            {

            }
        }

        public class ClassProtectedModifiers
        {
            public class Public
            { }

            internal class Internal
            { }

            protected internal class ProtectedInternal
            { }

            protected class Protected
            { }

            private protected class PrivateProtected
            { }

            private class Private
            { }
        }

        public class Public
        { }

        internal class Internal
        { }
    }
    //</assembly>
}